import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Heart, MessageCircle, Users } from "lucide-react";

export const Route = createFileRoute("/analytics")({
  head: () => ({ meta: [
    { title: "Instagram Analytics — Mira" }, { name: "description", content: "Monitor Instagram growth, engagement, reach, and recent post performance." },
    { property: "og:title", content: "Instagram Analytics — Mira" }, { property: "og:description", content: "See Instagram growth metrics and recent post performance." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: AnalyticsPage,
});

function AnalyticsPage(){const metrics=[['Followers','48.2K','+8.4%'],['Accounts reached','184K','+12.1%'],['Engagement rate','5.8%','+0.9%'],['Profile visits','12.4K','+6.3%']];const barHeights=['h-[38px]','h-[52px]','h-[44px]','h-[66px]','h-[81px]','h-[56px]','h-[42px]'];return <main className="page-wrap"><header className="page-heading"><div><p className="eyebrow">Performance</p><h1>Momentum, made visible</h1><p>A focused view of what’s growing and what your audience values.</p></div><span className="tiny-pill">Last 30 days</span></header>
  <section className="panel mb-5 flex flex-wrap items-center gap-4"><div className="grid size-14 place-items-center rounded-full bg-soft-purple font-display text-lg font-bold text-primary">NS</div><div className="mr-auto"><div className="flex items-center gap-2"><h2>@northstar.studio</h2><span className="grid size-4 place-items-center rounded-full bg-primary text-[9px] text-primary-foreground">✓</span></div><p className="mt-1 text-xs text-muted-foreground">Design studio · Connected</p></div><div className="flex gap-6 text-center"><div><strong className="block text-sm">428</strong><span className="text-xs text-muted-foreground">Posts</span></div><div><strong className="block text-sm">48.2K</strong><span className="text-xs text-muted-foreground">Followers</span></div></div></section>
  <section className="metric-grid mb-5">{metrics.map(([label,value,growth])=><div className="metric-card" key={label}><p>{label}</p><strong>{value}</strong><span><ArrowUpRight className="mr-1 inline size-3"/>{growth}</span></div>)}</section>
  <section className="grid gap-5 lg:grid-cols-[1fr_.65fr]"><div className="panel"><div className="panel-head"><div><p className="section-label mb-1">Recent posts</p><h2>Performance breakdown</h2></div></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Post</th><th>Format</th><th>Reach</th><th>Engagement</th></tr></thead><tbody>{[['A week in the studio','Reel','42.8K','7.2%'],['What clients actually need','Carousel','31.4K','6.8%'],['September moodboard','Carousel','24.1K','5.4%'],['Friday desk reset','Reel','18.7K','4.9%']].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={cell} className={i===0?'font-semibold':''}>{cell}</td>)}</tr>)}</tbody></table></div></div>
  <aside className="panel"><p className="section-label">Audience activity</p><h2 className="mt-1">Best time to post</h2><div className="mt-8 flex h-40 items-end gap-2">{barHeights.map((height,index)=><div key={height} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-sm bg-primary/20 ${height}`}><div className={index===4?'h-full rounded-t-sm bg-primary':'h-full rounded-t-sm bg-primary/35'}/></div><span className="text-[10px] text-muted-foreground">{['M','T','W','T','F','S','S'][index]}</span></div>)}</div><div className="mt-6 rounded-lg bg-soft-purple p-4"><p className="text-xs font-semibold text-primary">Friday · 6:00 PM</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Your audience is 2.4× more active than average.</p></div><div className="mt-5 flex flex-wrap gap-5 text-xs text-muted-foreground"><span><Users className="mr-1 inline size-3"/>71% followers</span><span><Heart className="mr-1 inline size-3"/>8.2K likes</span><span><MessageCircle className="mr-1 inline size-3"/>864 comments</span></div></aside></section>
</main>}